(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:1280,renderHeight:720,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};SETTINGS.quality='low';DEFAULT_ROUND_SETTINGS.quality='low';createUI();bindExpandedInput();await loadLevel(1,null,91831,null,true);
 const event=(type,key,repeat=false)=>{for(const f of testEvents.get(type)||[])f({key,repeat,target:{},preventDefault(){}});};
 let chords=0;
 for(const context of ['play','inventory','vendor','skills','title','death','loading'])for(const order of [['u','i'],['i','u']]){
  G.running=context!=='title';G.invOpen=['inventory','vendor'].includes(context);modalType=['vendor','skills','death'].includes(context)?context:'';G.paused=!!modalType;player.dead=context==='death';loadingLevel=context==='loading';TRADE.active=context==='vendor';const state=[G.invOpen,modalType,G.paused,TRADE.active];
  event('keydown',order[0]);event('keydown',order[1]);assert(DEV.open,'chord opens '+context+' '+order);assert(G.paused,'developer pauses');event('keydown',order[1],true);assert(DEV.open,'repeat does not toggle');event('keyup',order[0]);event('keyup',order[1]);event('keydown','escape');assert(!DEV.open,'escape closes');assert.deepStrictEqual([G.invOpen,modalType,G.paused,TRADE.active],state,'underlying view retained');event('keyup','escape');chords++;
 }
 G.running=true;G.invOpen=false;G.paused=false;modalType='';TRADE.active=false;player.dead=false;loadingLevel=false;
 event('keydown','i');assert(!G.invOpen);event('keyup','i');assert(G.invOpen,'I alone opens inventory');event('keydown','i');event('keyup','i');assert(!G.invOpen,'I alone closes inventory');event('keydown','u');for(const f of testEvents.get('blur')||[])f();assert(DEV.held.size===0,'blur resets physical chord');closeModal(false);
 showSkills();const noXp=JSON.stringify(trainingRecord());assert(!buyAttackUpgrade('whirlwind')&&JSON.stringify(trainingRecord())===noXp,'insufficient XP does not change ledger');closeModal(false);
 const gold=player.gold;assert(await developerGold());assert(player.gold===gold+10000,'exact gold grant');const owned=new Set(ownedEquipment().map(it=>it.id)),kit=await developerKit();assert(kit.length===9&&new Set(kit.map(it=>it.id)).size===9&&kit.every(it=>it.rarity===5&&it.locked),'nine unique locked Mythic pieces');assert(new Set(kit.filter(it=>it.slot!=='weapon').map(it=>it.armorSet)).size===1,'matching armor set');assert(ownedEquipment().length===owned.size+9&&[...owned].every(id=>ownedEquipment().some(it=>it.id===id)),'all prior items retained');assert([0,1,2].every(loadoutReady));const shield=kit.find(it=>it.slot==='offhand');for(const i of[1,2,0])assert(activateLoadout(i));assert(player.gear.offhand.id===shield.id,'shield returns');assert(new Set(ownedEquipment().map(it=>it.id)).size===owned.size+9);
 addXP(4000);showSkills();assert(buyAttackUpgrade('whirlwind')&&buyAttackUpgrade('volley'),'techniques bought for XP');const trained=trainingRecord(),clone=trainingRecord();clone.attacks.volley=3;assert(player.training.attacks.volley===1,'carry deep copies techniques');assert(validSave(makeSave()),'technique ledger save valid');const oldTraining=JSON.parse(JSON.stringify(makeSave()));delete oldTraining.player.training.attacks;delete oldTraining.player.training.attackEnabled;oldTraining.player.training.spent-=1200;oldTraining.player.training.bank+=1200;assert(validSave(oldTraining),'previous training saves remain compatible');const forged=JSON.parse(JSON.stringify(makeSave()));forged.player.training.attacks.whirlwind=3;assert(!validSave(forged),'unpaid technique rejected');forged.player.training.attacks.whirlwind=1;forged.player.training.attackEnabled.volley='yes';assert(!validSave(forged),'invalid switch rejected');closeModal(false);
 const ids=ownedEquipment().map(it=>it.id).sort().join(','),savedGold=player.gold;
 for(const d of[2,3,4,5,1]){assert(await developerWarp(d));assert(G.depth===d&&G.mode===(d===5?'outdoors':'dungeon'),'correct destination '+d);assert((d===4)===inCrucible(),'handmade arena only at floor4');assert(ownedEquipment().map(it=>it.id).sort().join(',')===ids&&player.gold===savedGold,'warp retains all owned gear and money');assert(JSON.stringify(trainingRecord())===JSON.stringify(trained),'warp retains training');assert(validSave(makeSave()),'valid destination save');}
 const raw=localStorage.getItem('deepvault.save.v2'),currentSeed=G.levelSeed,currentPlayer=player;RUN.shards=33;RUN.perks.force=4;RUN.elapsed=99;METER.dealt=234;localStorage.setItem('unrelated.application','keep');
 const set=localStorage.setItem;localStorage.setItem=(k,v)=>{if(k===EXPEDITION_ARCHIVE)throw new Error('quota');return set(k,v);};assert(!await resetFreshRound(),'quota prevents reset');assert(player===currentPlayer&&G.levelSeed===currentSeed&&RUN.shards===33,'failed reset leaves run intact');assert(localStorage.getItem('deepvault.save.v2')===raw,'failed reset does not overwrite save');localStorage.setItem=set;
 showResetRound();assert(await resetFreshRound());assert(player.level===1&&player.gold===45&&player.bag.length===2&&player.training.bank===0&&Object.values(player.training.attacks).every(n=>n===0),'fresh starter character');assert(RUN.shards===0&&RUN.perks.force===0&&RUN.elapsed===0&&METER.dealt===0,'run and combat progress wiped');assert(G.depth===1&&G.mode==='dungeon'&&localStorage.getItem('unrelated.application')==='keep','fresh dungeon and unrelated data retained');const archive=savedExpeditions(),exact=archive.find(r=>r.raw===raw);assert(exact,'previous autosave retained byte-for-byte');saveGame(true);assert(savedExpeditions().some(r=>r.raw===raw),'new autosave leaves archive intact');assert(await restoreArchivedExpedition(exact.id),'archived expedition restores');assert(player.gold===savedGold&&ownedEquipment().map(it=>it.id).sort().join(',')===ids,'restored gear and gold');assert(JSON.stringify(trainingRecord())===JSON.stringify(trained),'restored attack purchases');
 console.log('PASS: '+chords+' modal chord cases, I fallback, exact currency, nine-item kit and build ownership, all floor warps, XP validation, atomic quota failure, fresh-round reset and byte-exact restorable saves');engine.dispose();process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1);});
