(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:1280,renderHeight:720,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};SETTINGS.quality='low';createUI();await loadLevel(4,null,98765,null,true);
 const boss=G.bossRef,baseline=B7.makeEntity('abom_furnace',V3(64,GROUND,40));assert(Math.abs(boss.dmg/baseline.dmg-1.9)<1e-9,'abomination normal hit increased 90%');assert(Math.abs(specialDamage(boss,.8)/(baseline.dmg*.8)-3.42)<1e-9,'abomination specials increased 242%');killNode(baseline.rig.root);G.enemies=G.enemies.filter(e=>e!==baseline);const ordinary=B7.makeEntity('boneknight',V3(64,GROUND,40));assert(specialDamage(ordinary,.8)===ordinary.dmg*.8,'ordinary enemy damage unchanged');killNode(ordinary.rig.root);G.enemies=G.enemies.filter(e=>e!==ordinary);
 const counts=[0,0,0];for(const r of vendor.stock){const it=r.item;assert(it.rarity>=4&&it.ilvl>=18,'only high-level Legendary or Mythic stock');assert(Number.isFinite(it.score)&&r.price>sellValue(it),'finite stats, no resale arbitrage');if(it.slot==='weapon')counts[it.def.ranged||it.def.magic?2:it.hands===2?1:0]++;}assert(counts.every(n=>n>=10)&&vendor.stock.length>=60,'wide choice across all three playstyles');for(const slot of SLOTS.filter(s=>s!=='weapon'))assert(vendor.stock.filter(r=>r.item.slot===slot).length>=5,'five armor options per slot');
 let trials=0;while(!vendor.collections.length&&trials++<20){G.levelSeed++;vendor.stock=makePremiumStock();}assert(vendor.collections.length,'complete collections appear');player.pos.copyFrom(vendor.pos.add(V3(0,0,-1.5)));player.gold=1000000;showVendor();const collection=vendor.collections[0],rows=collectionRows(collection),cash=player.gold,n=player.bag.length,price=Math.round(rows.reduce((s,r)=>s+r.price,0)*.85);assert(new Set(rows.map(r=>r.item.slot)).size===6,'collection has six different slots');assert(buyVendorCollection(0),'bundle purchase');assert(player.gold===cash-price&&player.bag.length===n+6&&rows.every(r=>r.sold),'six actual items for exact discounted price');assert(!buyVendorCollection(0),'collection cannot be purchased twice');closeModal(false);
 const snapshot=JSON.parse(JSON.stringify(makeSave())),vRecord=JSON.stringify(vendorRecord());assert(validSave(snapshot));const corrupt=JSON.parse(JSON.stringify(snapshot));corrupt.vendor.collections={};assert(!validSave(corrupt),'malformed collections rejected');corrupt.vendor.collections=[{family:collection.family,ids:Array(6).fill(collection.ids[0])}];assert(!validSave(corrupt),'duplicate bundle identities rejected');
 const old=JSON.parse(JSON.stringify(snapshot));delete old.vendor.stockRevision;delete old.vendor.collections;const bossRow=old.enemies.find(e=>e.eid===boss.eid);bossRow.dmg/=1.9;delete bossRow.combatRevision;old.hazards=[{pos:[64,GROUND,60],radius:2,t:1,damage:baseline.dmg*.8,color:'#ffac70',kind:'fire',owner:boss.eid}];const beforeGold=player.gold,beforeBag=player.bag.map(it=>it.id).sort().join(',');await restoreSave(old);assert(Math.abs(G.bossRef.dmg-boss.dmg)<1e-9,'legacy boss damage migrated once');assert(Math.abs(WILD.hazards[0].damage-boss.dmg*.8*1.8)<1e-9,'legacy special damage migrated');assert(vendor.stock.every(r=>r.item.rarity>=4)&&player.gold===beforeGold&&player.bag.map(it=>it.id).sort().join(',')===beforeBag,'old stock upgraded without losing purchased items or currency');const migrated=makeSave(),damage=G.bossRef.dmg,hazardDamage=WILD.hazards[0].damage;await restoreSave(migrated);assert(G.bossRef.dmg===damage&&WILD.hazards[0].damage===hazardDamage,'reloading cannot compound boss damage');
 // Restore a purchased collection exactly, including every sold flag and price.
 await restoreSave(snapshot);assert(JSON.stringify(vendorRecord())===vRecord,'collection purchases and stock restore exactly');
 for(const e of G.enemies)killNode(e.rig.root);G.enemies=[];for(const h of WILD.hazards)killNode(h.mesh);WILD.hazards=[];player.pos.set(64,GROUND,70);player.rig.root.position.copyFrom(player.pos);const biome=biomeForDepth(),spawn=(kind,x,z,scale=1,yaw=0)=>placeProp(kind,V3(x,GROUND,z),biome,scale,true,yaw).metadata.destructible;
 // A shot must stop at the cover it destroys, not damage a foe behind it too.
 const box=spawn('supplycrate',64,64),center=box.min.add(box.max).scale(.5),foe=makeEntity('boneknight',V3(64,GROUND,61));foe.rig.root.position.copyFrom(foe.pos);const hp=foe.hp;fireProjectile(center.add(V3(0,0,4)),V3(0,0,-1),{speed:300,dmg:1,fromPlayer:true,color:'#e0cd9e'});stepProjectile(G.projectiles.at(-1),.04);assert(box.dead&&G.projectiles.length===0&&foe.hp===hp,'swept projectile breaks cover and is consumed before target');assert(WILD.broken.get(box.pid).dead,'projectile break persisted');fireProjectile(center.add(V3(0,0,4)),V3(0,0,-1),{speed:300,dmg:10,fromPlayer:true,color:'#e0cd9e'});stepProjectile(G.projectiles.at(-1),.04);assert(foe.hp<hp,'next shot reaches uncovered enemy');
 // Hostile shots and thin rotated geometry use the same impact path.
 const fence=spawn('fence',67,64,1,.73),local=V3(0,.8,0),target=BABYLON.Vector3.TransformCoordinates(local,fence.mesh.getWorldMatrix()),direction=BABYLON.Vector3.TransformNormal(V3(0,0,1),fence.mesh.getWorldMatrix()).normalize();fireProjectile(target.subtract(direction.scale(3)),direction,{speed:400,dmg:1,fromPlayer:false,color:'#ffac70'});stepProjectile(G.projectiles.at(-1),.02);assert(fence.dead&&G.projectiles.length===0,'fast hostile shot destroys thin rotated fence');
 const oak=spawn('oak',59.99,64.99,1.43,Math.PI/4);propIndex();assert((propBuckets.get(Math.floor(oak.max.x/5)+','+Math.floor(oak.max.z/5))||[]).includes(oak),'wide rotated canopy indexed to outer buckets');removeProp(oak,true);markCollisionDirty();
 // The handmade arena pillars and ground remain solid; visual light shafts do not.
 const a=.5*TAU/12,x=64+Math.cos(a)*30.9,z=64+Math.sin(a)*30.9,pillar=traceEnvironment(V3(x-3,10,z),V3(x+3,10,z));assert(pillar&&pillar.structural&&!pillar.prop,'batched arena pillar blocks shots');assert(traceEnvironment(V3(64,5,64),V3(64,-2,64))?.terrain,'ground blocks shots');assert(!traceEnvironment(V3(71,12,64),V3(77,12,64)),'transparent lighting is not a solid obstacle');
 // Open chest lids are checked at their actual animated orientation.
 const chest=G.crates[0];chest.open=true;chest.lid.rotation.x=1.85;chest.lid.computeWorldMatrix(true);const lidMesh=chest.lid.getChildMeshes()[0]||chest.lid,lidBounds=lidMesh.getBoundingInfo().boundingBox,lidCenter=lidBounds.minimumWorld.add(lidBounds.maximumWorld).scale(.5);G.time++;markCollisionDirty();assert(traceEnvironment(lidCenter.add(V3(0,0,3)),lidCenter.subtract(V3(0,0,3))),'raised chest lid remains solid');
 // Real muzzle converges on the reticle, without snapping to an off-center foe.
 killNode(foe.rig.root);G.enemies=[];const oldRay=cam.getForwardRay.bind(cam);cam.position.set(64,2.3,74);cam.getForwardRay=()=>new BABYLON.Ray(cam.position,V3(0,0,-1));const off=makeEntity('boneknight',V3(66,GROUND,64));off.rig.root.position.copyFrom(off.pos);player.pos.set(64,GROUND,70);player.yaw=0;player.aimPitch=0;player.rollT=-1;const targetProp=spawn('supplycrate',64,60,2),expected=traceEnvironment(cam.position,V3(64,2.3,40)).point;
 for(const kind of ['longbow','crossbow','emberstaff','repeater']){player.gear.weapon=makeItem('weapon',10,4,kind);player.gear.offhand=null;renderEquip(player);const anim=player.rig.anim;anim.atkT=.1;anim.atkStyle=player.stats.style;anim.phase=1;anim.phaseT=.5;updateRig(player,0);const muzzle=muzzleWorld(player).clone();shootPlayer();const shots=G.projectiles.filter(p=>p.fromPlayer);assert(shots.length===(kind==='repeater'?3:1),'all ranged firing modes preserved');assert(BABYLON.Vector3.Dot(shots[0].vel.normalizeToNew(),expected.subtract(muzzle).normalize())>.999999,'muzzle converges on reticle cover '+kind);for(const p of [...G.projectiles]){killNode(p.mesh);G.projectiles.splice(G.projectiles.indexOf(p),1);}}
 // A muzzle extended past cover must not spawn a projectile on its far side.
 player.gear.weapon=makeItem('weapon',10,4,'crossbow');renderEquip(player);player.rig.anim.atkT=.1;player.rig.anim.atkStyle=player.stats.style;player.rig.anim.phase=1;player.rig.anim.phaseT=.5;updateRig(player,0);const hand=player.rig.nodes.handR;hand.computeWorldMatrix(true);const muzzle=muzzleWorld(player),mid=hand.getAbsolutePosition().add(muzzle).scale(.5),cover=BABYLON.MeshBuilder.CreateBox('muzzle test cover',{size:.06},scene);cover.position.copyFrom(mid);world.props.push(cover);markCollisionDirty();shootPlayer();assert(G.projectiles.length===0,'hand-to-muzzle obstruction prevents spawning behind cover');world.props=world.props.filter(m=>m!==cover);killNode(cover);markCollisionDirty();cam.getForwardRay=oldRay;
 console.log('PASS: first-impact geometry, cover destruction/occlusion, hostile thin-wall impacts, wide prop buckets, arena structure, chest lids, reticle convergence, repeater, muzzle cover, premium stock/collections, exact transactions, save migration and stronger abomination damage');engine.dispose();process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1);});
