(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:640,renderHeight:360,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};showDetail=()=>{};refreshInv=()=>{};SETTINGS.quality='low';
 await loadLevel(1,null,104812,null,true);assert(G.running&&!loadingLevel,'floor one loaded');revealSurroundings(true);assert(surveyHas(player.pos.x,player.pos.z));assert(!surveyHas(0,0));assert([...SURVEY.chunks.values()].reduce((n,b)=>n+[...b].reduce((s,v)=>s+v.toString(2).replace(/0/g,'').length,0),0)<100,'initial reveal is small');
 const fixture={cells,vgrid,egrid,blockers:world.blockers,pos:player.pos.clone()};cells=new Uint8Array(CW*CH).fill(1);vgrid=new Uint32Array(GX*GY*GZ);egrid=new Uint32Array(vgrid.length);world.blockers=[];for(let z=0;z<CH;z++)cells[z*CW+11]=0;for(let x=44/VS;x<48/VS;x++)for(let z=0;z<GZ;z++)for(let y=2;y<GY;y++)vgrid[gi(x,y,z)]=1;
 SURVEY.reset();player.pos.set(41,GROUND,41);revealSurroundings(true);assert(surveyHas(41,41));assert(!surveyHas(49,41),'walls block revelation');assert(!surveyVisible(V3(49,GROUND,41),true));assert(!surveyHas(57,41),'limited radius');player.pos.set(49,GROUND,41);revealSurroundings(true);assert(surveyHas(41,41)&&surveyHas(49,41));assert(surveyVisible(V3(41,GROUND,41),false));assert(!surveyVisible(V3(41,GROUND,41),true),'remembered terrain does not reveal enemies through walls');cells=fixture.cells;vgrid=fixture.vgrid;egrid=fixture.egrid;world.blockers=fixture.blockers;player.pos.copyFrom(fixture.pos);SURVEY.reset();revealSurroundings(true);
 console.log('PASS: initial fog, occlusion and remembered terrain');const snapshot=JSON.parse(JSON.stringify(makeSave())),known=player.pos.clone();assert(validSave(snapshot));SURVEY.reset();await restoreSave(snapshot);assert(surveyHas(known.x,known.z),'saved exploration returns');const malformed=JSON.parse(JSON.stringify(snapshot));malformed.mapSurvey.chunks[0][1][0]=-1;assert(!validSave(malformed),'invalid bitset rejected');
 await loadLevel(3,playerCarry(),51842,null,true);G.bossRef.hp=1;killEnemy(G.bossRef);await descend();assert(G.depth===4&&G.running&&inCrucible(),'third floor leads to arena');assert(G.bossRef?.key==='abom_furnace'&&G.bossRef.spec.abomination,'unique thematic boss');assert(player.pos.x===64&&player.pos.z===94,'fixed safe arrival');assert(!crucibleLava(player.pos.x,player.pos.z));assert(clearPoint(vendor.pos.x,vendor.pos.z,.75)&&!crucibleLava(vendor.pos.x,vendor.pos.z),'merchant safe');assert(vendor.stock.length>=60&&RUN.forgePos&&RUN.shrinePos);
 assert(!solidWorld(64,20,64)&&solidWorld(64,29,64),'high ceiling actually traversable');assert(!walkableAt(100,64)&&walkableAt(64,64),'circular arena bounds');assert(crucibleLava(88,64)&&!crucibleLava(64,88),'lava ring and safe bridges');assert(world.chunks.every(m=>m.getTotalVertices()>0),'arena real nonempty geometry');assert(scene.getMaterialByName('flowing molten basalt')&&scene.particleSystems.length>=2,'lava and layered particles');assert(EXT.particles.emitRate===24,'quality settings preserve arena particles');assert(!surveyHas(64,64),'boss ring begins unexplored');await descend();assert(G.mode==='dungeon'&&G.depth===4,'boss locks survival');
 const safePos=player.pos.clone();player.pos.set(88,GROUND,64);player.invuln=0;player.blocking=true;player.guardAt=G.time;const hp=player.hp;adventureTick(.6);assert(player.hp<hp,'lava cannot be blocked or parried');player.pos.set(64,GROUND,88);player.invuln=0;const hp2=player.hp;adventureTick(.6);assert(player.hp===hp2,'bridge prevents lava damage');player.pos.copyFrom(safePos);player.hp=player.maxhp;player.blocking=false;
 G.bossRef.hp=Math.round(G.bossRef.maxhp*.61);const arena=JSON.parse(JSON.stringify(makeSave())),bossHP=G.bossRef.hp,bounds=world.chunks.map(m=>m.getTotalVertices()).join(',');assert(arena.arenaLayout===ARENA_LAYOUT&&validSave(arena));await restoreSave(arena);assert(G.bossRef.hp===bossHP&&inCrucible(),'arena boss health restored');assert(world.chunks.map(m=>m.getTotalVertices()).join(',')===bounds,'fixed arena regenerates identically');
 console.log('PASS: campaign route, arena geometry, lava and arena restoration');const legacy=JSON.parse(JSON.stringify(arena));delete legacy.arenaLayout;delete legacy.mapSurvey;legacy.depth=8;legacy.vendor.depth=8;legacy.player.gold=738;legacy.player.bag.push(itemRecord(makeItem('weapon',8,4,'longsword')));const itemIds=legacy.player.bag.map(i=>i.id).join(','),groundItem=itemRecord(makeItem('weapon',8,5,'pike')),potionsBefore=legacy.player.potions;legacy.drops.push({item:groundItem,pos:[64,1,64],isPotion:false},{item:null,pos:[64,1,64],isPotion:true});assert(validSave(legacy));await restoreSave(legacy);assert(G.depth===4&&G.bossRef.hp===G.bossRef.maxhp,'old late dungeon save migrates to fresh finale');assert(player.gold===738&&player.bag.slice(0,legacy.player.bag.length).map(i=>i.id).join(',')===itemIds,'migration retains inventory and gold');assert(player.bag.some(it=>it.id===groundItem.id)&&player.potions===potionsBefore+1,'migration rescues uncollected gear and potions');
 G.bossRef.hp=1;killEnemy(G.bossRef);frame();frame();assert(G.bossDown&&G.shaft,'next simulation step creates exit');await descend();assert(G.mode==='outdoors'&&G.depth===5&&WILD.depthBase===4,'survival unlocked after arena');SURVEY.reset();const visits=[[-65,-1],[-33,-33],[-31,-31],[-1,-1],[1,1],[31,3],[33,33]];for(const[x,z]of visits){player.pos.set(x,GROUND,z);revealSurroundings(true);assert(surveyHas(x,z));}assert([...SURVEY.chunks.values()].every(b=>b instanceof Uint32Array&&b.length===8));player.pos.set(500,GROUND,-500);streamWild(true);revealSurroundings(true);for(const[x,z]of visits)assert(surveyHas(x,z),'exploration survives chunk unloading');assert(!surveyVisible(V3(-65,GROUND,-1),true));startSurvivalWave();assert(WILD.wave===1&&G.depth===5,'new survival difficulty begins at floor five');for(const[x,z]of visits)assert(surveyHas(x,z));const wild=JSON.parse(JSON.stringify(makeSave()));assert(validSave(wild));await restoreSave(wild);for(const[x,z]of visits)assert(surveyHas(x,z),'negative coordinates persist');assert(!surveyHas(3401,-3901));assert(WILD.depthBase===4&&WILD.wave===1);delete wild.wild.depthBase;await restoreSave(wild);assert(WILD.depthBase===10,'legacy survival keeps its existing difficulty baseline');
 console.log('PASS: wall occlusion, remembered map, negative chunks, save validation, three floors, fixed arena, lighting geometry, lava, boss gate, migration and survival.');scene.dispose();engine.dispose();process.exit(0);
})().catch(e=>{console.error(e);process.exit(1);});
