(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:640,renderHeight:360,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};showDetail=()=>{};refreshInv=()=>{};
 await loadLevel(4,null,104812,null,true);console.log('CATALOG',JSON.stringify(CATALOG));assert(G.bossRef.spec.abomination,'Crucible abomination');const beforeMode=G.mode;await descend();assert(G.mode===beforeMode&&!loadingLevel,'guardian blocks departure');
 const c=G.crates[0],lip=V3(0,0,-1.05);c.mesh.rotation.y=.73;let minLift=100;for(let j=0;j<=30;j++){c.lid.rotation.x=1.85*j/30;c.lid.computeWorldMatrix(true);const point=BABYLON.Vector3.TransformCoordinates(lip,c.lid.getWorldMatrix());minLift=Math.min(minLift,point.y-c.pos.y);assert(point.y>c.pos.y+.99,'chest front never swings into chest');}console.log('CHEST minimum front-lip height',minLift.toFixed(3));
 // World matrices use Float32; 0.1 mm tolerance covers cancellation at the 94 m arena spawn.
 let samples=0;for(const key of['bat','glowmoth','stormdrake','dragonfly','owl']){const e=makeEntity(key,player.pos.clone()),r=e.rig;for(const yaw of[0,.7,2.1])for(let i=0;i<40;i++){e.yaw=yaw;r.anim.t=i*.067;r.anim.atkT=i%3===0?.1:-1;r.anim.phaseT=i/40;updateRig(e,0);for(const n of r.root.getDescendants())n.computeWorldMatrix(true);const inv=BABYLON.Matrix.Invert(r.nodes.body.getWorldMatrix()),pts=r.wingTips.map(n=>BABYLON.Vector3.TransformCoordinates(BABYLON.Vector3.TransformCoordinates(V3(.47,0,0),n.getWorldMatrix()),inv));assert(Math.abs(pts[0].y-pts[1].y)<.0001&&Math.abs(pts[0].x+pts[1].x)<.0001&&Math.abs(pts[0].z-pts[1].z)<.0001,'synchronized mirrored wing tips '+key);samples++;}killNode(r.root);G.enemies=G.enemies.filter(q=>q!==e);}console.log('WINGS',samples,'symmetric poses');
 const deadBoss=makeEntity('abom_choir',player.pos.clone());deadBoss.rig.anim.death=2;updateRig(deadBoss,0);const corpse=deadBoss.rig.secondaryArms.map(q=>q.upper.rotation.asArray());deadBoss.rig.anim.t+=3;updateRig(deadBoss,0);assert(JSON.stringify(corpse)===JSON.stringify(deadBoss.rig.secondaryArms.map(q=>q.upper.rotation.asArray())),'dead secondary arms settle');killNode(deadBoss.rig.root);G.enemies=G.enemies.filter(e=>e!==deadBoss);
 const setKey=Object.keys(ARMOR_SETS)[0];for(const s of ['head','chest','legs'])player.gear[s]=makeItem(s,2,0,setKey);const alt={...makeItem('head',1,0,Object.keys(ARMOR_SETS)[1]),score:player.gear.head.score+1};player.bag=[alt];const utility=loadoutScore(player.gear);autoEquip();assert(loadoutScore(player.gear)>=utility,'auto-equip preserves set utility');
 let drops=0,commons=0,ultra=0;for(let i=0;i<30000;i++){const results=rollObjectLoot({kind:'barrel',material:'wood',pid:'distribution:'+i});drops+=results.length;for(const q of results){if(q.kind==='gear'&&q.rarity<2){commons++;assert(q.level<=G.depth*.65+2,'ordinary object gear below enemy loot level');}if(q.rarity>=4)ultra++;}}assert(drops>23000&&commons>13000&&ultra>0&&ultra<80,'common object supplies, exceptional rare gear');console.log('DESTRUCTION rewards',drops,'ordinary gear',commons,'legendary/mythic',ultra);
 const p=[...destructibles.values()].find(p=>!p.dead&&p.material==='wood');assert(p&&p.max.y>p.min.y,'wood exists');const pid=p.pid;damageProp(p,999999,p.pos);const rewardState=[player.gold,G.drops.length];assert(p.dead&&!world.blockers.includes(p.blocker),'destroy removes obstacle');damageProp(p,999999,p.pos);assert(JSON.stringify(rewardState)===JSON.stringify([player.gold,G.drops.length]),'no duplicate reward');const snap=makeSave();assert(validSave(snap),'dungeon destruction save valid');await restoreSave(snap);assert(destructibles.get(pid)?.dead,'broken dungeon object persists');
 G.bossRef.hp=1;killEnemy(G.bossRef);assert(G.bossDown,'abomination opens exit');const bagIds=player.bag.map(i=>i.id).join(',');await descend();assert(G.mode==='outdoors'&&G.depth===5&&!loadingLevel,'dungeon exits into outdoors');assert(player.bag.map(i=>i.id).join(',')===bagIds,'bag survives transition');assert(WILD.chunks.size===25,'high quality bounded chunks');assert(world.chunks.every(m=>m.getVerticesData(BABYLON.VertexBuffer.PositionKind).length>0),'outdoor terrain actual vertices');assert(walkableAt(-10000,70000)&&!solidWorld(-10000,groundAt(-10000,70000),70000),'unbounded horizontal world');assert(vendor?.stock.length>=60,'refuge vendor');console.log('OUTDOOR',WILD.chunks.size,'chunks',destructibles.size,'props',G.enemies.length,'wildlife');
 const prop=[...destructibles.values()].find(p=>!p.dead&&p.kind==='supplycrate')||[...destructibles.values()].find(p=>!p.dead),propId=prop.pid,chunkId=prop.chunk;damageProp(prop,999999,prop.pos);const home=player.pos.clone();const chest=G.crates[0];if(chest){chest.open=true;WILD.opened.add(chest.pid);}const chestId=chest?.pid;player.pos.set(300,GROUND,-250);streamWild(true);assert(WILD.chunks.size===25&&!WILD.chunks.has(chunkId),'distant chunks unload');assert(!G.enemies.some(e=>e.passive&&!WILD.chunks.has(e.chunk)),'unloaded animals removed');player.pos.copyFrom(home);streamWild(true);assert(destructibles.get(propId)?.dead,'destroyed streamed object stays destroyed');if(chestId)assert(G.crates.find(c=>c.pid===chestId)?.open,'streamed chest stays open');
 // One remaining spawn must not clear the wave in the same simulation step.
 WILD.wave=1;WILD.pending=1;WILD.phase='spawning';WILD.spawnClock=0;tickSurvival(.01);assert(WILD.phase==='fighting'&&G.enemies.some(e=>e.waveId===1&&!e.dead),'last spawn counted before wave completion');for(const e of G.enemies.filter(e=>e.waveId===1))killEnemy(e);tickSurvival(.01);assert(WILD.phase==='intermission','wave clears after last enemy death');
 WILD.wave=9;startSurvivalWave();const abom=G.bossRef;assert(WILD.wave===10&&abom.spec.abomination&&abom.waveId===10,'wave ten abomination');WILD.pending=0;tickSurvival(.01);assert(WILD.phase==='fighting'&&!WILD.portal,'boss blocks regional gate');const elite=makeEntity('boneknight',player.pos.add(V3(15,0,0)),{elite:true,eliteType:'tempest'});elite.waveId=10;elite.stunned=1;elite.specialCd=0;elite.aggro=30;elite.lastSeen=player.pos.clone();const hazardN=WILD.hazards.length;updateEnemy(elite,.1);assert(WILD.hazards.length===hazardN,'stunned elite cannot cast');
 const outdoorSave=makeSave();assert(validSave(outdoorSave),'outdoor save valid');const remembered={eliteId:elite.eid,hp:elite.maxhp,dmg:elite.dmg,speed:elite.speed,stock:JSON.stringify(vendorRecord())};SETTINGS.quality='low';await restoreSave(outdoorSave);assert(WILD.wave===10&&WILD.pending===0&&WILD.chunks.size===9,'active wave restores on lower quality');assert(!G.enemies.some(e=>e.passive&&!WILD.chunks.has(e.chunk)),'restored animals own resident chunks');const restored=G.enemies.find(e=>e.eid===remembered.eliteId);assert(restored.eliteType==='tempest'&&restored.ability==='storm'&&restored.maxhp===remembered.hp&&restored.dmg===remembered.dmg&&restored.speed===remembered.speed,'elite identity and exact scaling restore');assert(JSON.stringify(vendorRecord())===remembered.stock,'camp stock persists');
 for(const e of G.enemies.filter(e=>e.waveId===10&&!e.dead))killEnemy(e);tickSurvival(.01);assert(WILD.phase==='gate'&&WILD.portal&&!G.shaft,'clear abomination wave creates outdoor gate');const gateSave=makeSave(),cash=player.gold;await restoreSave(gateSave);tickSurvival(.01);assert(WILD.phase==='gate'&&WILD.portal&&player.gold===cash,'gate restore does not duplicate rewards');const oldCamp=WILD.camp.clone();advanceWildRegion();assert(WILD.region===1&&WILD.phase==='intermission'&&WILD.wave===10&&BABYLON.Vector3.Distance(oldCamp,WILD.camp)>200,'gate advances region and preserves wave');assert(vendor&&BABYLON.Vector3.Distance(vendor.pos,WILD.camp)<8,'vendor moves with refuge');assert(WILD.chunks.size===9,'resident chunks bounded after gate');const save2=makeSave();assert(validSave(save2),'new region saves');
 console.log('PASS: outward hinges, mirrored wings, settled death appendages, armor set optimization, object loot distribution/persistence, three-floor campaign and arena exit, streamed biomes, wave completion, abomination gate, elite restoration, quality change, camp relocation');engine.dispose();
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
