const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const dist=path.resolve(__dirname,'../dist');
const nodes=new Map();
const context2d=new Proxy({createRadialGradient:()=>({addColorStop(){}}),measureText:s=>({width:s.length*8}),getImageData:()=>({data:new Uint8ClampedArray(64*64*4)}),canvas:{width:64,height:64}},{get:(o,k)=>k in o?o[k]:(()=>{})});
function node(id=''){if(nodes.has(id))return nodes.get(id);const attrs={};const n={id,style:{},width:220,height:200,innerHTML:'',textContent:'',value:'',checked:false,disabled:false,children:[],classList:{add(){},remove(){},toggle(){},contains(){return false;}},prepend(x){this.children.unshift(x);},appendChild(x){this.children.push(x);return x;},remove(){},addEventListener(){},removeEventListener(){},setAttribute(k,v){attrs[k]=String(v);},getContext:()=>context2d,focus(){document.activeElement=this;},getBoundingClientRect:()=>({left:0,top:0,width:100,height:100}),querySelectorAll:()=>[],getAttribute:k=>attrs[k]??null,lastChild:null,click(){},setPointerCapture(){},insertAdjacentHTML(){}};let inner='';Object.defineProperty(n,'innerHTML',{get:()=>inner,set:v=>{inner=v;n.children=[];}});Object.defineProperty(n,'firstElementChild',{get:()=>n.children[0]});Object.defineProperty(n,'lastChild',{get:()=>n.children.at(-1)});Object.defineProperty(n,'firstChild',{get:()=>n.children[0]});n.remove=function(){for(const parent of nodes.values()){const idx=parent.children.indexOf(n);if(idx>=0)parent.children.splice(idx,1);}};nodes.set(id,n);return n;}
const document={removeEventListener(){},readyState:'loading',getElementById:node,createElement:tag=>node(tag+Math.random()),body:node('body'),documentElement:node('html'),addEventListener(){},exitPointerLock(){},querySelectorAll:()=>[],pointerLockElement:null,hidden:false};
global.document=document;global.window={document,addEventListener(){},devicePixelRatio:1};global.OffscreenCanvas=class{constructor(w,h){this.width=w;this.height=h;}getContext(){return context2d;}};
const B=require(path.join(dist,'vendor/babylon.js'));
const storage=new Map(),events=new Map();const sandbox={BABYLON:B,window:{BABYLON:B,document,devicePixelRatio:1},document,navigator:{getGamepads:()=>[],maxTouchPoints:0},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},console,setTimeout:(f,ms)=>ms<=30?setTimeout(f,0):0,clearTimeout,requestAnimationFrame(){},addEventListener(type,fn){if(!events.has(type))events.set(type,[]);events.get(type).push(fn);},matchMedia:()=>({matches:false}),performance,HTMLInputElement:class{},HTMLSelectElement:class{},Blob,URL,assert};
sandbox.window.localStorage=sandbox.localStorage;
const c=vm.createContext(sandbox);const html=fs.readFileSync(path.join(dist,'index.html'),'utf8');const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];const base=scripts.at(-1)[1];const ext=fs.readFileSync(path.join(dist,'expansion.js'),'utf8');vm.runInContext(base+'\n'+ext+'\n'+fs.readFileSync(path.join(dist,'articulation.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'menagerie.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'frontier.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'market.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'crucible.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'loadouts.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'combat.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'horizons.js'),'utf8')+'\n'+fs.readFileSync(path.join(dist,'arsenal.js'),'utf8'),c);

c.process=process;c.testEvents=events;module.exports={c,vm,fs};
