(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:1280,renderHeight:720,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};SETTINGS.quality='low';createUI();bindExpandedInput();
 await loadLevel(1,null,314159,null,true);assert(G.running&&!loadingLevel&&RUN.class==='wayfarer');assert(!document.getElementById('veilBox').innerHTML.includes('data-class='),'no role selector');assert([0,1,2].every(loadoutReady),'three starter builds ready');assert(ownedEquipment().every(it=>it&&it.id));const ids=()=>ownedEquipment().map(it=>it.id).sort((a,b)=>a-b).join(','),originalIds=ids(),armor=player.gear.chest.id,helm=player.gear.head.id,shield=player.gear.offhand.id;
 for(let i=0;i<30;i++){assert(activateLoadout(i%3));assert(player.gear.chest.id===armor&&player.gear.head.id===helm,'sparse weapon-only builds keep armor');assert(ids()===originalIds,'switching preserves exact item ownership');assert(new Set([...player.bag,...Object.values(player.gear)].filter(Boolean).map(it=>it.id)).size===ownedEquipment().length);if(player.gear.weapon.hands===2)assert(player.gear.offhand===null&&!player.equipMeshes.offhand,'two-handed gear stows shield mesh/stats');else assert(player.gear.offhand.id===shield,'shared shield returns');}
 const alternate=makeItem('head',7,3),sharedUpgrade=makeItem('chest',7,2);player.bag.push(alternate,sharedUpgrade);const wornHead=player.gear.head.id;G.invOpen=true;$('inv').style.display='block';selectLoadoutTab(1);assert(assignLoadoutItem(alternate));assert(player.gear.head.id===wornHead,'editing inactive build does not equip');assert(LOADOUTS.builds[1].head===alternate.id);assert(activateLoadout(1,true)&&player.gear.head.id===alternate.id);selectLoadoutTab(-1);assert(assignLoadoutItem(sharedUpgrade));assert(player.gear.chest.id===sharedUpgrade.id,'shared armor equipped');G.invOpen=false;$('inv').style.display='none';activateLoadout(0);assert(player.gear.head.id===alternate.id&&player.gear.chest.id===sharedUpgrade.id,'unpinned slots keep currently worn armor even from another build');activateLoadout(1);assert(player.gear.head.id===alternate.id,'specific override restored');clearLoadoutSlot('head',1);assert(player.gear.head.id===alternate.id,'clear override keeps currently worn gear');
 // With neither a default nor a pinned slot, retain the already worn item.
 delete LOADOUTS.shared.head;activateLoadout(2);assert(player.gear.head.id===alternate.id,'fully blank slot keeps existing gear');LOADOUTS.shared.head=alternate.id;
 const ranged=player.gear.weapon;player.rig.anim.atkT=.12;player.rig.anim.atkDur=.8;player.rig.anim.prevPts=[V3()];player.rig.anim.propPrev=[V3()];player.rig.anim.didShot=true;player.blocking=true;const hp=player.hp,stam=player.stam;activateLoadout(0);assert(player.rig.anim.atkT===-1&&!player.rig.anim.prevPts&&!player.rig.anim.propPrev&&!player.blocking&&player.atkCd>=.22,'attack switch cancels obsolete sweep and keeps recovery');assert(player.hp<=hp&&player.stam<=stam,'switch cannot heal or refill stamina');
 const key=(key,repeat=false)=>{for(const fn of testEvents.get('keydown')||[])fn({key,repeat,target:null,preventDefault(){}});};key('2');assert(LOADOUTS.active===1,'hotkey two');key('3');assert(LOADOUTS.active===2,'hotkey three');key('v');assert(LOADOUTS.active===0,'cycle hotkey');key('v',true);assert(LOADOUTS.active===0,'held key does not cycle repeatedly');G.paused=true;key('3');assert(LOADOUTS.active===0,'pause blocks hotkey');G.paused=false;G.invOpen=true;key('3');assert(LOADOUTS.active===0,'inventory blocks combat hotkeys');G.invOpen=false;
 const lock=makeItem('hands',2,0),junk=makeItem('legs',1,0),bound=makeItem('feet',3,1);player.bag.push(lock,junk,bound);assert(toggleItemLock(lock)&&lock.locked);LOADOUTS.builds[2].feet=bound.id;const coins=player.gold;assert(!sellableItems().includes(lock)&&!sellableItems().includes(bound));sellCommonGear();assert(player.bag.some(it=>it.id===lock.id)&&player.bag.some(it=>it.id===bound.id)&&!player.bag.some(it=>it.id===junk.id)&&player.gold>coins,'forge sale protects locks and saved gear');
 player.pos.copyFrom(vendor.pos.add(V3(0,0,-1.5)));showVendor();switchTradeSide('player');selected=lock;showDetail(lock);assert($('btnDrop').disabled&&!$('btnLock').hidden,'merchant shows lock and disables sale');assert(!sellVendorItem(lock)&&!sellVendorItem(bound),'individual sale also protected');const junk2=makeItem('legs',1,0);player.bag.push(junk2);sellAllUnequipped();assert(ownedEquipment().some(it=>it.id===lock.id)&&ownedEquipment().some(it=>it.id===bound.id)&&!ownedEquipment().some(it=>it.id===junk2.id),'bulk protects locked and inactive build gear');assert(toggleItemLock(lock)&&!lock.locked);assert(sellVendorItem(lock),'unlock permits deliberate individual sale');closeModal(false);
 const save=JSON.parse(JSON.stringify(makeSave())),savedBuilds=JSON.stringify(loadoutRecord()),saveIds=ids();assert(validSave(save));const bad=JSON.parse(JSON.stringify(save));bad.player.loadouts.builds[1].head='bad';assert(!validSave(bad));await restoreSave(save);assert(JSON.stringify(loadoutRecord())===savedBuilds&&ids()===saveIds,'builds persist through export restore');await loadLevel(2,playerCarry(),1146,null,true);assert(JSON.stringify(loadoutRecord())===savedBuilds,'builds carry across floors');
 const legacy=JSON.parse(JSON.stringify(makeSave()));delete legacy.player.loadouts;legacy.run.class='arcanist';assert(validSave(legacy));await restoreSave(legacy);assert(RUN.class==='wayfarer'&&ids()===saveIds,'old role save migrates without losing gear');assert([0,1,2].every(loadoutReady));console.log('PASS: universal starter, sparse/shared builds, item ownership, shield, editing, hotkeys, attack safety, all sell paths, legacy and persistent saves');
 await loadLevel(4,playerCarry(),98765,null,true);player.pos.set(64,GROUND,64);player.rig.root.position.copyFrom(player.pos);const oldBlocks=world.blockers,oldSolid=solidWorld;world.blockers=[];indexBlockers();solidWorld=()=>0;SETTINGS.shake=false;const viewport=new BABYLON.Viewport(0,0,1280,720);for(const yaw of[0,.8,Math.PI/2,Math.PI,4.7])for(const pitch of[-.6,0,.2,.95]){mouse.yaw=yaw;mouse.pitch=pitch;updateCamera(1);cam.getViewMatrix(true);cam.getProjectionMatrix(true);const focus=player.pos.add(V3(0,1.48,0)),right=V3(Math.cos(yaw),0,-Math.sin(yaw)),screen=BABYLON.Vector3.Project(focus,BABYLON.Matrix.Identity(),cam.getTransformationMatrix(),viewport);assert(BABYLON.Vector3.Dot(cam.position.subtract(focus),right)>1.04,'camera stays on physical right');assert(screen.x<1280*.45&&screen.x>1280*.35,'player left of reticle');}
 solidWorld=oldSolid;mouse.yaw=0;mouse.pitch=-.6;updateCamera(1);assert(cameraPointClear(cam.position)&&cam.position.y>.95,'looking upward keeps the camera above the real floor');mouse.yaw=0;mouse.pitch=0;solidWorld=(x,y,z)=>x>64.4&&x<64.65&&z>61.9&&z<62.2?1:0;updateCamera(1);const focus=player.pos.add(V3(0,1.48,0));assert(BABYLON.Vector3.Distance(cam.position,focus)<3,'angled boom detects wall missed by centerline');assert(cameraPointClear(cam.position));solidWorld=oldSolid;world.blockers=[{x:64.525,z:61.6,r:.5,height:20}];indexBlockers();updateCamera(1);assert(BABYLON.Vector3.Distance(cam.position,focus)<3&&cameraPointClear(cam.position),'camera avoids tall pillar');
 solidWorld=(x,y,z)=>x>64.8||z<62.7?1:0;world.blockers=[];indexBlockers();for(const yaw of[0,.7,1.8,3,4.2,5.8]){mouse.yaw=yaw;updateCamera(.016);assert(cameraPointClear(cam.position),'smoothed camera avoids corner clipping');}solidWorld=oldSolid;world.blockers=oldBlocks;indexBlockers();
 activateLoadout(2);mouse.yaw=0;mouse.pitch=0;player.yaw=yawTo(V3(0,0,1));player.rig.root.rotation.y=player.yaw;updateRig(player,0);updateCamera(1);const enemies=G.enemies;G.enemies=[];const muzzle=muzzleWorld(player).clone(),aim=cam.position.add(cam.getForwardRay().direction.scale(50));shootPlayer();const shot=G.projectiles.at(-1);assert(shot?.fromPlayer&&BABYLON.Vector3.Dot(shot.vel.normalizeToNew(),aim.subtract(muzzle).normalize())>.9999,'projectiles follow actual shoulder-camera ray from weapon');G.enemies=enemies;
 const protectedItem=makeItem('hands',3,2);player.bag.push(protectedItem);toggleItemLock(protectedItem);const preSurvival=JSON.stringify(loadoutRecord());G.bossDown=true;await descend();assert(G.mode==='outdoors'&&JSON.stringify(loadoutRecord())===preSurvival&&player.bag.some(it=>it.id===protectedItem.id&&it.locked),'survival keeps builds and locks');const surface=JSON.parse(JSON.stringify(makeSave()));await restoreSave(surface);assert(JSON.stringify(loadoutRecord())===preSurvival&&player.bag.some(it=>it.id===protectedItem.id&&it.locked));
 console.log('PASS: right-shoulder projection across 20 poses, angled-wall/pillar/corner collision, camera-ray projectile aiming, arena and survival carry');scene.dispose();engine.dispose();process.exit(0);
})().catch(err=>{console.error(err);process.exit(1);});
