(async()=>{
 // Catalog budgets need no renderer. Check all comparable slots and identities.
 let checked=0;
 for(const level of[1,10,40,200]){
  const weaponBands=Array.from({length:6},()=>({min:Infinity,max:0,dmin:Infinity,dmax:0}));
  for(let rarity=0;rarity<6;rarity++)for(const kind of Object.keys(WEAPONS))for(let roll=0;roll<4;roll++){
   const it=makeItem('weapon',level,rarity,kind),b=weaponBands[rarity],dps=weaponDps(it);b.min=Math.min(b.min,it.score);b.max=Math.max(b.max,it.score);b.dmin=Math.min(b.dmin,dps);b.dmax=Math.max(b.dmax,dps);assert(Number.isFinite(it.score)&&it.baseDmg>0,'finite weapon '+kind);for(const [k,cap]of Object.entries(PERCENT_CAPS))assert(it.stats[k]<=cap+.0001,'bounded percentage '+k);checked++;
  }
  for(let rarity=1;rarity<6;rarity++){assert(weaponBands[rarity].min>weaponBands[rarity-1].max,'weapon rarity score order '+level+' '+rarity+' '+JSON.stringify(weaponBands));assert(weaponBands[rarity].dmin>weaponBands[rarity-1].dmax,'weapon rarity DPS order');}
  for(const slot of SLOTS.filter(s=>s!=='weapon')){const bands=Array.from({length:6},()=>({min:Infinity,max:0,emin:Infinity,emax:0}));for(let rarity=0;rarity<6;rarity++)for(const family of Object.keys(ARMOR_SETS))for(let roll=0;roll<4;roll++){const it=makeItem(slot,level,rarity,family),b=bands[rarity],ehp=defenseGain(it);b.min=Math.min(b.min,it.score);b.max=Math.max(b.max,it.score);b.emin=Math.min(b.emin,ehp);b.emax=Math.max(b.emax,ehp);assert(it.stats.armor>0&&it.stats.hp>0,'defensive core');checked++;}for(let rarity=1;rarity<6;rarity++){assert(bands[rarity].min>bands[rarity-1].max,'armor rarity score order '+slot+' '+level+' '+rarity+' '+JSON.stringify(bands));assert(bands[rarity].emin>bands[rarity-1].emax,'armor rarity defense order '+slot+' '+level+' '+rarity);}}
 }
 const item=makeItem('weapon',10,4,'repeater');item.upgrades=4;item.baseDmg*=Math.pow(1.1,4);item.score=itemScore(item);const record=itemRecord(item),seed=SEED,restored=reviveItem(JSON.parse(JSON.stringify(record)));assert(Math.abs(item.baseDmg-restored.baseDmg)<.000001,'tempering does not compound on restore');assert(SEED===seed,'migration does not consume procedural random');const malformed=reviveItem({...record,balanceSeed:'bad',upgrades:'bad'});assert(Number.isFinite(malformed.score)&&malformed.upgrades===0,'malformed metadata normalized safely');const legacy={...record};delete legacy.balanceVersion;delete legacy.balanceSeed;const a=reviveItem(legacy),b=reviveItem(itemRecord(a));assert(JSON.stringify(a.stats)===JSON.stringify(b.stats)&&a.baseDmg===b.baseDmg,'legacy migration idempotent');assert(a.id===item.id&&a.name===item.name&&a.upgrades===4,'legacy identity/tempering preserved');console.log('RARITY',checked,'items: score, weapon DPS and armor defense bands ordered at levels 1, 10, 40, 200');
 engine=new BABYLON.NullEngine({renderWidth:1280,renderHeight:720,textureSize:256});canvas=$('stage');
 initPreview=()=>{if(pvEngine)return;pvEngine=new BABYLON.NullEngine({renderWidth:400,renderHeight:220,textureSize:256});pvScene=new BABYLON.Scene(pvEngine);pvCam=new BABYLON.ArcRotateCamera('preview',-Math.PI/2,Math.PI/2.3,3,V3(),pvScene);};
 createUI();await loadLevel(1,null,1234567,null,true);player.pos.copyFrom(vendor.pos.add(V3(0,0,-1.5)));player.gold=100000;player.potions=14;showVendor();assert(TRADE.active&&G.invOpen&&G.paused&&modalType==='vendor','shared inventory trading opens and pauses');assert(inventoryItems().length===vendor.stock.filter(r=>!r.sold).length&&inventoryPotionCount()===Infinity,'stock and potion availability');assert($('bag').children.filter(e=>e.className?.startsWith('cell')).length===BAG_PAGE_SIZE+1,'stock uses paginated inventory cells plus potion');
 showDetail(player.gear.weapon);assert($('btnEquip').disabled&&$('btnEquip').textContent==='Equipped','equipped gear never offered for purchase');bagFilter='weapon';refreshInv();const focused=inventoryFocusNodes.get('category:weapon');focused.focus();refreshInv();assert(document.activeElement.getAttribute('data-focus-key')==='category:weapon'&&document.activeElement!==focused,'focus preserved across redraw');assert($('bag').children.filter(e=>e.className?.startsWith('cell')).length===inventoryItems().filter(i=>i.slot==='weapon').length,'weapon category counts correct');
 const pickItem=vendor.stock.find(r=>r.item.slot==='weapon').item;selected=pickItem;showDetail(pickItem);assert(pvMesh&&pvMesh.isVisible&&pvMesh.getTotalVertices()>0,'vendor selection has real preview geometry');assert($('dInfo').innerHTML.includes('If equipped')&&$('dInfo').innerHTML.includes('Character stat'),'replacement comparison rendered');const previewId=pvMesh.uniqueId,stats0=JSON.stringify(player.stats),hp0=player.hp;comparisonHtml(pickItem);assert(JSON.stringify(player.stats)===stats0&&player.hp===hp0,'comparison has no gameplay mutation');
 const index=vendor.stock.findIndex(r=>r.item===pickItem),price=vendor.stock[index].price,cash=player.gold,count=player.bag.length;assert(buyVendorItem(index)&&player.gold===cash-price&&player.bag.length===count+1,'purchase exact transfer');assert(!buyVendorItem(index),'no duplicate purchase');
 switchTradeSide('player');assert(inventoryItems()===player.bag&&TRADE.side==='player','own satchel view');selected=pickItem;showDetail(pickItem);assert(pvMesh.uniqueId!==previewId,'preview updates after source switch');const sellPrice=sellValue(pickItem),saleCash=player.gold;assert(sellVendorItem(pickItem)&&player.gold===saleCash+sellPrice&&!player.bag.includes(pickItem),'individual item sale');assert(!sellVendorItem(pickItem),'repeated sale rejected');const equipped=player.gear.weapon;player.bag.push(equipped);assert(!sellVendorItem(equipped)&&player.gear.weapon===equipped,'equipped reference protected');assert(!sellVendorItem(ELIXIR)&&player.potions===14,'potions protected');
 const great=makeItem('weapon',5,3,'greatsword');player.gear.weapon=makeItem('weapon',2,1,'longsword');player.gear.offhand=makeItem('offhand',2,1,'garrison');computeStats(player);const plan=replacementGear(great);assert(plan.removed.length===2&&plan.gear.offhand===null,'two-handed comparison removes shield');assert(comparisonHtml(great).includes(player.gear.offhand.name),'removed shield named');assert(comparisonHtml(great).includes('Block absorbed')&&inspectLoadout(plan.gear).guard<inspectLoadout(player.gear).guard,'shield blocking compared');
 player.potCd=.8;showDetail(ELIXIR);assert($('btnEquip').disabled&&$('btnEquip').textContent.includes('Recovering'),'paused potion cooldown shown');player.potCd=0;const beforePotions=player.potions;assert(buyVendorPotion()&&player.potions===beforePotions+1,'potions buy from either tab');player.gold=0;assert(!buyVendorPotion(),'insufficient potion funds');const unsold=vendor.stock.findIndex(r=>!r.sold);assert(!buyVendorItem(unsold),'insufficient item funds');player.gold=100000;
 // Pagination uses current source, and tabs restore their own filter/page.
 player.bag=Array.from({length:110},()=>makeItem('head',3,2));bagFilter='armor';bagPage=2;refreshInv();assert($('bag').children.filter(e=>e.className?.startsWith('cell')).length===14,'satchel pagination');switchTradeSide('vendor');assert(bagFilter==='weapon','stock filter remembered');switchTradeSide('player');assert(bagFilter==='armor'&&bagPage===2,'satchel filter/page remembered');
 const save=makeSave(),vendorState=JSON.stringify(vendorRecord());assert(validSave(save),'balanced save valid');closeModal(false);assert(!TRADE.active&&!G.invOpen&&!G.paused,'merchant closes completely');assert(!buyVendorItem(unsold),'stale buy outside trade rejected');await restoreSave(save);assert(JSON.stringify(vendorRecord())===vendorState,'vendor items/prices/sold flags persist');assert(player.bag.every(i=>i.balanceVersion===4),'inventory balance persists');
 // Full-body transforms: 45-degree local yaw and real ranged release alignment.
 let poses=0,maxGrip=0;player.pos.copyFrom(roomCenterWorld(startRoom));player.rollT=-1;for(const kind of Object.keys(WEAPONS)){const it=makeItem('weapon',5,3,kind);player.gear.weapon=it;player.gear.offhand=null;renderEquip(player);const r=player.rig;assert(Math.abs(r.hitNode.rotationQuaternion.y-Math.sin(Math.PI/8))<1e-7,'clockwise grip '+kind);for(const yaw of[0,.8,2.1])for(const pitch of[-.4,0,.4]){player.yaw=yaw;player.aimPitch=pitch;r.anim.atkT=.1;r.anim.atkStyle=player.stats.style;r.anim.phase=1;r.anim.phaseT=.52;updateRig(player,0);r.hitNode.computeWorldMatrix(true);assert(BABYLON.Vector3.Distance(r.hitNode.getAbsolutePosition(),r.hitNode.parent.getAbsolutePosition())<.00002,'origin grip stays attached');if(it.hands===2&&it.def.shape!=='bow'&&r.weaponMeta.grip2){const target=BABYLON.Vector3.TransformCoordinates(V3(...r.weaponMeta.grip2),r.hitNode.getWorldMatrix()),error=BABYLON.Vector3.Distance(target,r.nodes.handL.getAbsolutePosition());maxGrip=Math.max(maxGrip,error);assert(error<.025,'support hand attached');}if(['bow','crossbow'].includes(it.def.shape)){const forward=BABYLON.Vector3.TransformNormal(V3(0,0,-1),r.hitNode.getWorldMatrix()).normalize(),expected=BABYLON.Vector3.TransformNormal(V3(0,-Math.sin(pitch),-Math.cos(pitch)),r.root.getWorldMatrix()).normalize();assert(BABYLON.Vector3.Distance(forward,expected)<.0001,'ranged muzzle aimed '+kind);if(it.def.shape==='bow'){const string=r.bowString.getVerticesData(BABYLON.VertexBuffer.PositionKind),nock=V3(...string.slice(3,6));assert(BABYLON.Vector3.Distance(nock,r.bowArrow.position)<.00001,'arrow sits at string nock');}}poses++;}}
 console.log('GRIPS',poses,'release poses; max support-hand error',maxGrip);console.log('PASS: merchant grid/categories, actual previews, replacement comparisons, purchases, individual sales, ownership, potions, pagination, save migration, grip rotation, aimed ranged release');engine.dispose();if(pvEngine)pvEngine.dispose();
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
