(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:1280,renderHeight:720,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};SETTINGS.quality='low';createUI();await loadLevel(4,null,87191,null,true);
 for(const e of G.enemies)killNode(e.rig.root);G.enemies=[];player.pos.set(64,GROUND,64);player.rig.root.position.copyFrom(player.pos);player.yaw=0;player.aimPitch=0;player.moveSpeedNow=0;player.vel.set(0,0,0);player.rollT=-1;addXP(15000);showSkills();for(const k of Object.keys(ATTACK_UPGRADES))for(let n=0;n<3;n++)assert(buyAttackUpgrade(k));assert(validSave(makeSave()));assert(!buyAttackUpgrade('volley'),'max purchase rejected');closeModal(false);
 let hits=0,poses=0,maxGrip=0,maxJoint=0;
 for(const kind of ['longsword','greatsword','spear','scythe']){
  player.gear.weapon=makeItem('weapon',5,3,kind);player.gear.offhand=null;renderEquip(player);player.yaw=.7;const a=player.rig.anim;a.combo=2;startAttack(player,player.stats.style,{windup:.01,active:.01,recover:.01});assert(a.technique==='whirlwind'&&a.ac>=.65,'extreme haste preserves full spin duration');
  const targets=[];for(let n=0;n<16;n++){const angle=n*TAU/16,t=makeEntity('boneknight',player.pos.add(V3(Math.cos(angle)*1.15,0,Math.sin(angle)*1.15)));t.rig.root.position.copyFrom(t.pos);targets.push(t);}const counts=new Map();
  for(let t=0;t<a.atkDur+.02;t+=1/60){if(!tickAttack(player,1/60))break;if(a.phase===1)sweepHit(player,targets,e=>counts.set(e,(counts.get(e)||0)+1));updateRig(player,1/60);}
  assert(counts.size===targets.length,kind+' 360 sweep hit '+counts.size+'/'+targets.length);assert([...counts.values()].every(n=>n===1),'one damage event per enemy');hits+=counts.size;for(const e of targets){killNode(e.rig.root);G.enemies=G.enemies.filter(q=>q!==e);}updateRig(player,0);assert(player.rig.root.rotation.y===player.yaw,'rotation resets after attack');
 }
 for(const kind of ['longsword','greatsword','spear','scythe','longbow','crossbow','emberstaff','repeater']){
  player.gear.weapon=makeItem('weapon',5,3,kind);player.gear.offhand=null;renderEquip(player);const r=player.rig,a=r.anim;a.combo=2;startAttack(player,player.stats.style,{windup:.3,active:.2,recover:.3});
  for(const yaw of[0,.8,2.1])for(const pitch of[-1.42,-.5,0,.95])for(const phase of[0,1,2])for(let j=0;j<=12;j++){
   player.yaw=yaw;player.aimPitch=pitch;a.atkT=.1;a.phase=phase;a.phaseT=j/12;updateRig(player,0);const rotation=r.root.rotation.y;updateRig(player,0);assert(r.root.rotation.y===rotation&&player.yaw===yaw,'zero-time rig updates do not accumulate yaw');
   for(const limb of Object.values(r.chains))for(const[upper,lower,length]of[[limb.upper,limb.lower,limb.l1],[limb.lower,limb.end,limb.l2]]){const err=Math.abs(BABYLON.Vector3.Distance(upper.getAbsolutePosition(),lower.getAbsolutePosition())-length);assert(err<.0001,'bone length fixed');maxJoint=Math.max(maxJoint,err);}
   if(player.gear.weapon.hands===2&&player.gear.weapon.def.shape!=='bow'&&r.weaponMeta.grip2){const grip=BABYLON.Vector3.TransformCoordinates(V3(...r.weaponMeta.grip2),r.hitNode.getWorldMatrix()),err=BABYLON.Vector3.Distance(grip,r.nodes.handL.getAbsolutePosition());maxGrip=Math.max(maxGrip,err);assert(err<.025,'two hand grip '+kind+' pitch '+pitch+' phase '+phase+' t '+j/12+' error '+err);}
   poses++;
  }cancelEquipmentAttack();updateRig(player,0);assert(r.root.rotation.y===player.yaw,'switch/cancel resets spin');
 }
 player.yaw=0;player.aimPitch=0;mouse.yaw=Math.PI;player.pos.set(64,GROUND,70);player.rig.root.position.copyFrom(player.pos);const ray=cam.getForwardRay.bind(cam);cam.position.set(64,2.3,74);cam.getForwardRay=()=>new BABYLON.Ray(cam.position,V3(0,0,-1));const clearShots=()=>{for(const p of G.projectiles)killNode(p.mesh);G.projectiles=[];};
 let volleyCases=0;
 for(const kind of ['longbow','crossbow','emberstaff','repeater'])for(const rank of[0,1,2,3]){
  player.training.attacks.volley=rank;player.gear.weapon=makeItem('weapon',5,3,kind);player.gear.offhand=null;renderEquip(player);const a=player.rig.anim;a.combo=0;startAttack(player,player.stats.style,{windup:.3,active:.2,recover:.3});a.atkT=.4;a.phase=1;a.phaseT=.52;const muzzle=muzzleWorld(player),aim=aimPointFromCamera(60);shootPlayer();assert(G.projectiles.length===(kind==='repeater'?3:1)+rank*2,'correct volley/repeater count');assert(BABYLON.Vector3.Dot(G.projectiles[0].vel.normalizeToNew(),aim.subtract(muzzle).normalize())>.999999,'central shot exact reticle');assert(G.projectiles.every(p=>BABYLON.Vector3.Distance(p.mesh.position,muzzle)<.001),'all shots originate at actual muzzle');assert(G.projectiles.every(p=>p.dmg>0&&p.dmg<=G.projectiles[0].dmg*1.001),'balanced satellite damage');clearShots();volleyCases++;
 }
 player.training.attacks.volley=3;player.gear.weapon=makeItem('weapon',5,3,'crossbow');renderEquip(player);const a=player.rig.anim;a.combo=0;startAttack(player,player.stats.style,{windup:.3,active:.2,recover:.3});a.atkT=.4;a.phase=1;a.phaseT=.52;
 // Satellite rays use a local fan even when aiming nearly vertically.
 for(const pitch of[-1.42,.95]){player.aimPitch=pitch;const d=V3(0,-Math.sin(pitch),-Math.cos(pitch));cam.position.copyFrom(player.pos.add(V3(0,2,3)));cam.getForwardRay=()=>new BABYLON.Ray(cam.position,d);shootPlayer();assert(G.projectiles.length===7);const center=G.projectiles[0].vel.normalizeToNew();for(let i=1;i<7;i+=2){const left=G.projectiles[i].vel.normalizeToNew(),right=G.projectiles[i+1].vel.normalizeToNew();assert(Math.abs(BABYLON.Vector3.Dot(left,center)-BABYLON.Vector3.Dot(right,center))<1e-8,'symmetric steep-aim fan');}clearShots();}
 player.aimPitch=0;cam.position.set(64,2.3,74);cam.getForwardRay=()=>new BABYLON.Ray(cam.position,V3(0,0,-1));updateRig(player,0);const muzzle=muzzleWorld(player),hand=player.rig.nodes.handR;hand.computeWorldMatrix(true);const cover=BABYLON.MeshBuilder.CreateBox('technique muzzle cover',{size:.08},scene);cover.position.copyFrom(hand.getAbsolutePosition().add(muzzle).scale(.5));world.props.push(cover);markCollisionDirty();shootPlayer();assert(G.projectiles.length===0,'obstructed muzzle cancels entire volley');world.props=world.props.filter(m=>m!==cover);killNode(cover);markCollisionDirty();
 const box=placeProp('supplycrate',V3(64,GROUND,64),biomeForDepth(),2,true,0).metadata.destructible;shootPlayer();assert(G.projectiles.length===7);for(const p of [...G.projectiles])stepProjectile(p,.12);assert(box.dead,'volley destroys breakable cover');assert(G.projectiles.length<7,'cover consumes intersecting projectile');clearShots();cam.getForwardRay=ray;
 console.log('PASS: '+hits+' real weapon 360-degree hits, '+poses+' full-body technique poses, maximum grip error '+maxGrip.toFixed(6)+', bone error '+maxJoint.toFixed(7)+', '+volleyCases+' firing modes, steep symmetric fans, exact reticle and muzzle-cover collision');engine.dispose();process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1);});
