(async()=>{
 engine=new BABYLON.NullEngine({renderWidth:640,renderHeight:360,textureSize:256});canvas=$('stage');initPreview=()=>{};showPreview=()=>{};SETTINGS.quality='low';createUI();await loadLevel(5,null,104812,null,true,'outdoors');assert(G.mode==='outdoors'&&!loadingLevel);
 const near=(a,b,message,tol=1e-5)=>assert(Math.abs(a-b)<tol,message+': '+a+' vs '+b);
 let samples=0,maxVertexError=0,maxInterpError=0,minHeight=Infinity,maxHeight=-Infinity,maxSlope=0;const vertexMap=new Map();
 for(const chunk of WILD.chunks.values()){
  const m=chunk.terrain,P=m.getVerticesData(BABYLON.VertexBuffer.PositionKind),N=m.getVerticesData(BABYLON.VertexBuffer.NormalKind),I=m.getIndices();m.computeWorldMatrix(true);
  for(let i=0;i<P.length;i+=3){const x=P[i],y=P[i+1],z=P[i+2],key=x+','+z,old=vertexMap.get(key);near(y,surfaceAt(x,z),'render vertex matches sample');maxVertexError=Math.max(maxVertexError,Math.abs(y-surfaceAt(x,z)));minHeight=Math.min(minHeight,y);maxHeight=Math.max(maxHeight,y);if(old){for(let j=0;j<3;j++)near(N[i+j],old.n[j],'shared vertex normals');near(y,old.y,'shared vertex height');}else vertexMap.set(key,{y,n:[N[i],N[i+1],N[i+2]]});}
  for(let i=0;i<I.length;i+=21){const a=I[i]*3,b=I[i+1]*3,c=I[i+2]*3,x=P[a]*.21+P[b]*.36+P[c]*.43,y=P[a+1]*.21+P[b+1]*.36+P[c+1]*.43,z=P[a+2]*.21+P[b+2]*.36+P[c+2]*.43;maxInterpError=Math.max(maxInterpError,Math.abs(y-surfaceAt(x,z)));near(y,surfaceAt(x,z),'triangle interior matches sample');samples++;}
 }
 for(let x=-300;x<300;x+=2.3)for(let z=-300;z<300;z+=2.7){const eps=.002,dx=(surfaceAt(x+eps,z)-surfaceAt(x-eps,z))/(2*eps),dz=(surfaceAt(x,z+eps)-surfaceAt(x,z-eps))/(2*eps);maxSlope=Math.max(maxSlope,Math.hypot(dx,dz));}
 console.log('TERRAIN',{chunks:WILD.chunks.size,trianglesSampled:samples,maxVertexError,maxInterpError,minHeight,maxHeight,maxSlope,maxAngleDegrees:Math.atan(maxSlope)*180/Math.PI});
 const ground=(e,label)=>near(e.pos.y,groundAt(e.pos.x,e.pos.z)+(e.spec?.fly?(e.floatY??e.spec.fly):0),label);
 ground(player,'initial player');for(const e of G.enemies)ground(e,'initial wildlife '+e.key);
 const oldWorldProps=world.props.length;let checkedProps=0;for(const p of destructibles.values()){if(p.dead)continue;near(p.mesh.position.y,groundAt(p.pos.x,p.pos.z)-.2,'prop placement '+p.kind);near(p.pos.y,p.mesh.position.y,'prop record '+p.kind);const b=p.mesh.getHierarchyBoundingVectors();near(b.min.y,p.min.y,'prop bounds min '+p.kind);near(b.max.y,p.max.y,'prop bounds max '+p.kind);checkedProps++;}
 for(const c of G.crates){near(c.pos.y,groundAt(c.pos.x,c.pos.z),'chest pos');near(c.mesh.position.y,c.pos.y,'chest mesh');}
 near(vendor.pos.y,groundAt(vendor.pos.x,vendor.pos.z),'vendor');near(vendor.rig.root.position.y,vendor.pos.y,'vendor mesh');
 console.log('GROUNDED OBJECTS',{props:checkedProps,chests:G.crates.length,wildlife:G.enemies.length});
 const quad=G.enemies.find(e=>e.rig.quadChains),enemy=makeEntity('skeleton',V3(9,999,9)),flyer=makeEntity('bat',V3(10,999,10));
 for(const [x,z]of[[12,10],[14,13],[20,18],[-10,-15],[-19,-21]]){player.pos.set(x,999,z);stepMove(player,.17,.15);ground(player,'stepMove player');player.rig.root.position.copyFrom(player.pos);updatePlayer(1/60);ground(player,'updatePlayer');for(const e of[enemy,flyer,...(quad?[quad]:[])]){e.pos.set(x+3,999,z+2);stepMove(e,.13,-.17);ground(e,'stepMove '+e.key);e.rig.root.position.copyFrom(e.pos);updateEnemy(e,1/60);const floatOffset=e.passive&&e.spec.fly?e.spec.fly+Math.sin(G.time*1.6+e.eid)*.35:e.spec?.fly?(e.floatY??e.spec.fly):0;near(e.pos.y,groundAt(e.pos.x,e.pos.z)+floatOffset,'updateEnemy '+e.key);}}
 SETTINGS.autoLoot=false;spawnDrop(makeItem('head',1,0),V3(8,99,8));const drop=G.drops.at(-1);near(drop.mesh.position.y,groundAt(8,8)+.55,'drop mesh');near(drop.halo.position.y,groundAt(8,8)+.04,'drop halo');updateDrops(1/60);near(drop.mesh.position.y,groundAt(8,8)+.55+Math.sin(drop.t*2.2)*.09,'drop tick');
 let raySamples=0,maxRayError=0;for(let i=0;i<60;i++){const a=V3(-22+(i*7.31)%65,0,-24+(i*4.61)%66);a.y=surfaceAt(a.x,a.z)+.1+(i%4)*.7;const b=a.add(V3(2+Math.sin(i*1.72)*9,-.5-(i%5)*.25,Math.cos(i*.7)*8));const delta=b.subtract(a),L=delta.length(),ray=new BABYLON.Ray(a,delta.scale(1/L),L),actual=terrainImpact(a,b);let expected=null;for(const c of WILD.chunks.values()){const hit=ray.intersectsMesh(c.terrain,false);if(hit.hit&&hit.distance<=L&&(expected===null||hit.distance/L<expected))expected=hit.distance/L;}assert((actual===null)===(expected===null),'ray presence '+i+' '+actual+' '+expected);if(actual!==null){maxRayError=Math.max(maxRayError,Math.abs(actual-expected));near(actual,expected,'exact terrain ray '+i,2e-5);}raySamples++;}
 console.log('MOTION & RAYS',{raySamples,maxRayError});
 const snap=makeSave();assert(validSave(snap),'save valid');for(const a of snap.enemies)a.pos[1]=1;for(const a of snap.crates)a.pos[1]=1;snap.player.pos[1]=1;await restoreSave(snap);ground(player,'restored player');for(const c of G.crates){near(c.pos.y,groundAt(c.pos.x,c.pos.z),'restored chest');near(c.mesh.position.y,c.pos.y,'restored chest mesh');}for(const e of G.enemies)ground(e,'restored '+e.key);console.log('PASS: terrain mesh/physics agreement, shared seams, prop/chest bounds and elevations, player/animal/enemy grounding, exact ray traces, old flat save reprojection');engine.dispose();
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
